"""add websites table

Revision ID: bfe8a6c2c34b
Revises: c7f24509e72c
Create Date: 2026-09-16 08:14:28.668025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe8a6c2c34b'
down_revision: Union[str, None] = 'c7f24509e72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('static', 'dynamic', name='website_type'), nullable=False),
    sa.Column('framework', sa.Enum('html', 'react', 'flask', 'fastapi', 'node', name='website_framework'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'building', 'online', 'stopped', 'failed', 'deleting', name='website_status'), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('internal_port', sa.Integer(), nullable=True),
    sa.Column('public_url', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_owner_id'), 'websites', ['owner_id'], unique=False)
    op.create_index(op.f('ix_websites_slug'), 'websites', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_websites_slug'), table_name='websites')
    op.drop_index(op.f('ix_websites_owner_id'), table_name='websites')
    op.drop_table('websites')
    # ### end Alembic commands ###
