"""add admin dashboard: audit_logs, system_metrics, users.is_active

Revision ID: db832c5e430a
Revises: bfe8a6c2c34b
Create Date: 2026-09-16 17:38:32.346377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db832c5e430a'
down_revision: Union[str, None] = 'bfe8a6c2c34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('memory_percent', sa.Float(), nullable=False),
    sa.Column('disk_percent', sa.Float(), nullable=False),
    sa.Column('network_rx_bytes', sa.BigInteger(), nullable=False),
    sa.Column('network_tx_bytes', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_metrics_timestamp', 'system_metrics', ['timestamp'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    # server_default is required here -- existing rows need a value
    # for this new NOT NULL column at ALTER TABLE time. All existing
    # users become active, matching the model's Python-side default.
    op.add_column(
        'users',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # The server_default was only needed to backfill existing rows;
    # drop it so future inserts rely on the application-level default
    # in app/models/user.py, keeping one source of truth.
    op.alter_column('users', 'is_active', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_system_metrics_timestamp', table_name='system_metrics')
    op.drop_table('system_metrics')
    # ### end Alembic commands ###
